// SPDX-FileCopyrightText: 2026 OVH SAS <opensource@ovh.net>
//
// SPDX-License-Identifier: Apache-2.0

package testutils

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/asn1"
	"encoding/pem"
	"fmt"
	"math/big"
	"os"
	"path/filepath"
	"testing"
	"time"
)

type TestCert struct {
	CertPEM []byte
	KeyPEM  []byte
}

const (
	rsaBits      = 4096
	organization = "OVHcloud"

	okmsSANPrefix = "okms.domain:"
)

var (
	subjectAltNameOID = asn1.ObjectIdentifier{2, 5, 29, 17}
	okmsUPNOID        = asn1.ObjectIdentifier{1, 3, 6, 1, 4, 1, 311, 20, 2, 3}
)

// certOptions holds the optional knobs for GenerateTestCert.
type certOptions struct {
	okmsID string
}

// CertOption customizes a certificate generated by GenerateTestCert.
type CertOption func(*certOptions)

// WithOkmsID embeds the given KMS instance id as an "okms.domain:<id>" otherName in the
// certificate's Subject Alternative Name, matching what GetOkmsIDFromCert reads.
func WithOkmsID(okmsID string) CertOption {
	return func(o *certOptions) { o.okmsID = okmsID }
}

func publicKey(priv any) any {
	switch k := priv.(type) {
	case *rsa.PrivateKey:
		return &k.PublicKey
	case *ecdsa.PrivateKey:
		return &k.PublicKey
	default:
		return nil
	}
}

// GenerateTestCert creates a self-signed certificate for tests.
// Supports "rsa" or "ecdsa".
func GenerateTestCert(algorithm string, opts ...CertOption) (*TestCert, error) {
	var options certOptions
	for _, opt := range opts {
		opt(&options)
	}

	var priv any
	var err error

	switch algorithm {
	case "ecdsa":
		priv, err = ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	case "rsa":
		priv, err = rsa.GenerateKey(rand.Reader, rsaBits)
	default:
		return nil, fmt.Errorf("unsupported algorithm: %s", algorithm)
	}
	if err != nil {
		return nil, fmt.Errorf("failed to generate private key: %w", err)
	}

	serialNumberLimit := new(big.Int).Lsh(big.NewInt(1), 128)
	serialNumber, err := rand.Int(rand.Reader, serialNumberLimit)
	if err != nil {
		return nil, fmt.Errorf("failed to generate serial number: %w", err)
	}

	template := x509.Certificate{
		SerialNumber: serialNumber,
		Subject: pkix.Name{
			Organization: []string{organization},
		},
		NotBefore: time.Now(),
		NotAfter:  time.Now().Add(24 * time.Hour),

		KeyUsage:              x509.KeyUsageDigitalSignature,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
	}

	if options.okmsID != "" {
		ext, err := okmsSANExtension(options.okmsID)
		if err != nil {
			return nil, fmt.Errorf("build okms SAN extension: %w", err)
		}
		template.ExtraExtensions = append(template.ExtraExtensions, ext)
	}

	certBytes, err := x509.CreateCertificate(rand.Reader, &template, &template, publicKey(priv), priv)
	if err != nil {
		return nil, fmt.Errorf("failed to create certificate:: %w", err)
	}
	certPEM := pem.EncodeToMemory(&pem.Block{
		Type:  "CERTIFICATE",
		Bytes: certBytes,
	})

	keyBytes, err := x509.MarshalPKCS8PrivateKey(priv)
	if err != nil {
		return nil, fmt.Errorf("marshal private key: %w", err)
	}
	keyPEM := pem.EncodeToMemory(&pem.Block{
		Type:  "PRIVATE KEY",
		Bytes: keyBytes,
	})

	return &TestCert{
		CertPEM: certPEM,
		KeyPEM:  keyPEM,
	}, nil
}

// okmsSANExtension builds a SubjectAltName extension carrying a single otherName
// ("okms.domain:<okmsID>") under the Microsoft UPN OID, as produced by the OVHcloud KMS.
func okmsSANExtension(okmsID string) (pkix.Extension, error) {
	nameValue, err := asn1.Marshal(okmsSANPrefix + okmsID)
	if err != nil {
		return pkix.Extension{}, err
	}
	explicitValue, err := asn1.Marshal(asn1.RawValue{
		Class:      asn1.ClassContextSpecific,
		Tag:        0,
		IsCompound: true,
		Bytes:      nameValue,
	})
	if err != nil {
		return pkix.Extension{}, err
	}
	oid, err := asn1.Marshal(okmsUPNOID)
	if err != nil {
		return pkix.Extension{}, err
	}
	otherName, err := asn1.Marshal(asn1.RawValue{
		Class:      asn1.ClassContextSpecific,
		Tag:        0,
		IsCompound: true,
		Bytes:      append(oid, explicitValue...),
	})
	if err != nil {
		return pkix.Extension{}, err
	}
	sanValue, err := asn1.Marshal(asn1.RawValue{
		Class:      asn1.ClassUniversal,
		Tag:        asn1.TagSequence,
		IsCompound: true,
		Bytes:      otherName,
	})
	if err != nil {
		return pkix.Extension{}, err
	}
	return pkix.Extension{Id: subjectAltNameOID, Value: sanValue}, nil
}

func WriteDataToTempFile(t *testing.T, dir, name string, data []byte) string {
	t.Helper()

	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, data, 0o0600); err != nil {
		t.Fatalf("write temp file failed: %v", err)
	}

	return path
}
